const users = [
  {
    name: "John",
    Heartrate: 98,
    BP_Systolic: 95,
    BP_Diastolic: 72,
    Respiratory_Rate: 15,
    Temp: 99.1,
    Sleep_Duration: 8.9,
    Sleep_Quantity: "Good",
    Sleep_Consistency: "High",
    Steps: 8561,
    Active_Minutes: 85,
    Strength_Training: "No",
    Water_Intake: 3.2,
    Weight: 54.8,
    BMI: 30.6,
    Age: 45,
    Oxygen_Level: 92,
    Blood_Sugar: 112.7,
  },
  {
    name: "Jane",
    Heartrate: 88,
    BP_Systolic: 105,
    BP_Diastolic: 79,
    Respiratory_Rate: 16,
    Temp: 99.4,
    Sleep_Duration: 5.5,
    Sleep_Quantity: "Average",
    Sleep_Consistency: "Low",
    Steps: 3719,
    Active_Minutes: 55,
    Strength_Training: "Yes",
    Water_Intake: 3.0,
    Weight: 51.8,
    BMI: 28.7,
    Age: 58,
    Oxygen_Level: 92,
    Blood_Sugar: 81.4,
  },
  {
    name: "Alice",
    Heartrate: 74,
    BP_Systolic: 118,
    BP_Diastolic: 89,
    Respiratory_Rate: 12,
    Temp: 98.8,
    Sleep_Duration: 8.1,
    Sleep_Quantity: "Good",
    Sleep_Consistency: "Moderate",
    Steps: 7506,
    Active_Minutes: 41,
    Strength_Training: "Yes",
    Water_Intake: 2.7,
    Weight: 59.5,
    BMI: 21.6,
    Age: 53,
    Oxygen_Level: 93,
    Blood_Sugar: 70.9,
  },
  {
    name: "Bob",
    Heartrate: 67,
    BP_Systolic: 92,
    BP_Diastolic: 74,
    Respiratory_Rate: 14,
    Temp: 98.5,
    Sleep_Duration: 8.6,
    Sleep_Quantity: "Average",
    Sleep_Consistency: "High",
    Steps: 12700,
    Active_Minutes: 88,
    Strength_Training: "Yes",
    Water_Intake: 2.4,
    Weight: 117.4,
    BMI: 24.4,
    Age: 54,
    Oxygen_Level: 90,
    Blood_Sugar: 103.8,
  },
  {
    name: "Charlie",
    Heartrate: 80,
    BP_Systolic: 109,
    BP_Diastolic: 62,
    Respiratory_Rate: 15,
    Temp: 98.0,
    Sleep_Duration: 7.6,
    Sleep_Quantity: "Good",
    Sleep_Consistency: "Low",
    Steps: 4741,
    Active_Minutes: 89,
    Strength_Training: "No",
    Water_Intake: 3.7,
    Weight: 88.5,
    BMI: 31.4,
    Age: 38,
    Oxygen_Level: 98,
    Blood_Sugar: 93.6,
  },
  {
    name: "David",
    Heartrate: 98,
    BP_Systolic: 125,
    BP_Diastolic: 82,
    Respiratory_Rate: 12,
    Temp: 99.3,
    Sleep_Duration: 6.8,
    Sleep_Quantity: "Good",
    Sleep_Consistency: "High",
    Steps: 10766,
    Active_Minutes: 63,
    Strength_Training: "No",
    Water_Intake: 2.8,
    Weight: 117.6,
    BMI: 27.6,
    Age: 25,
    Oxygen_Level: 97,
    Blood_Sugar: 108.9,
  },
  {
    name: "Eve",
    Heartrate: 78,
    BP_Systolic: 108,
    BP_Diastolic: 67,
    Respiratory_Rate: 18,
    Temp: 99.2,
    Sleep_Duration: 6.5,
    Sleep_Quantity: "Good",
    Sleep_Consistency: "Moderate",
    Steps: 4998,
    Active_Minutes: 95,
    Strength_Training: "Yes",
    Water_Intake: 2.7,
    Weight: 80.3,
    BMI: 18.6,
    Age: 72,
    Oxygen_Level: 97,
    Blood_Sugar: 116.2,
  },
  {
    name: "Frank",
    Heartrate: 82,
    BP_Systolic: 115,
    BP_Diastolic: 79,
    Respiratory_Rate: 15,
    Temp: 97.1,
    Sleep_Duration: 6.1,
    Sleep_Quantity: "Poor",
    Sleep_Consistency: "High",
    Steps: 11321,
    Active_Minutes: 101,
    Strength_Training: "No",
    Water_Intake: 1.6,
    Weight: 71.8,
    BMI: 31.1,
    Age: 26,
    Oxygen_Level: 99,
    Blood_Sugar: 73.5,
  },
  {
    name: "Grace",
    Heartrate: 70,
    BP_Systolic: 92,
    BP_Diastolic: 75,
    Respiratory_Rate: 17,
    Temp: 97.1,
    Sleep_Duration: 9.6,
    Sleep_Quantity: "Poor",
    Sleep_Consistency: "High",
    Steps: 3403,
    Active_Minutes: 29,
    Strength_Training: "Yes",
    Water_Intake: 2.4,
    Weight: 85.4,
    BMI: 19.1,
    Age: 64,
    Oxygen_Level: 95,
    Blood_Sugar: 79.8,
  },
  {
    name: "Harry",
    Heartrate: 70,
    BP_Systolic: 108,
    BP_Diastolic: 72,
    Respiratory_Rate: 18,
    Temp: 97.9,
    Sleep_Duration: 9.0,
    Sleep_Quantity: "Average",
    Sleep_Consistency: "High",
    Steps: 12521,
    Active_Minutes: 42,
    Strength_Training: "Yes",
    Water_Intake: 2.5,
    Weight: 80.8,
    BMI: 30.8,
    Age: 32,
    Oxygen_Level: 96,
    Blood_Sugar: 114.7,
  },
];


export default users;